name       : tdb
version    : 1.3.12
release    : 10
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.3.12.tar.gz : 60134e32253cac8e2efe5e0185d20123c208bcf6ad15edf2f50d80daadf8c348
license    : LGPL-3.0
component  : database
summary    : Transactional database
description: |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
