name       : tdb
version    : 1.3.15
release    : 9
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.3.15.tar.gz : b4a1bf3833601bd9f10aff363cb750860aef9ce5b4617989239923192f946728
license    : LGPL-3.0
component  : database
summary    : Transactional database
description: |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
