name       : tdb
version    : 1.4.4
release    : 19
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.4.4.tar.gz : 59a16937de4b75e949405757f7b6bb0084d589cad98ae9001f9b7ec73b3c6380
license    : LGPL-3.0-or-later
component  :
    - database
    - utils : database
summary    : Transactional database
description: |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
builddeps  :
    - pkgconfig(libtirpc)
patterns   :
    - utils : /usr/bin
setup      : |
    %patch -p1 < $pkgfiles/Fix-invalid-syntax-in-tdb-header.patch
    %configure \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
# check      : |
# Disable tests until upstream get it together
#    %make check
