name        : tdb
version     : 1.3.7
release     : 6
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.3.7.tar.gz : a64d95ca0cc06a28fed24c6e952aed7660cae04983108735d6bc30b925136412
license     : GPL-2.0+
summary     : Transactional database
description : |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
patterns   :
    - utils: /usr/bin
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
