name        : tdb
version     : 1.3.6
release     : 5
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.3.6.tar.gz : 85d7dd247e58d8b303de542a2bc39a3dff9e5f54dea39a94c1c910cee25a59a5
license     : GPL-2.0+
summary     : Transactional database
description : |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
patterns   :
    - utils: /usr/bin
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
