name       : tdb
version    : 1.3.16
release    : 12
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.3.16.tar.gz : 6a3fc2616567f23993984ada3cea97d953a27669ffd1bfbbe961f26e0cf96cc5
license    : LGPL-3.0-or-later
component  : database
summary    : Transactional database
description: |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
patterns   :
    - utils : /usr/bin
setup      : |
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace \
               --disable-rpath-install
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
